# yaml-language-server: $schema=../../Documents/PowerShell/Modules/OkUnity/config.schema.json
builds:
  global:
  - c:/builds/editor/*
  - d:/work/unity*/build/WindowsEditor
  project:
  - c:/p4/*/Unity/Editor

# TODO: consumer places to check
#
# ~/AppData/Roaming/UnityHub/editors.json
# C:\Program Files\Unity\Editor
# C:\Program Files\Unity\Hub\Editor\*
