# COMMON

[".local/docs/nerd-fonts"]
    type = "archive"
    url = "https://github.com/just3ws/nerd-font-cheatsheets/archive/refs/heads/master.tar.gz"
    refreshPeriod = "168h"
    exact = true
    include = ["*", "*/*.md"]
    stripComponents = 1

[".config/alacritty/themes"]
    type = "archive"
    url = "https://github.com/alacritty/alacritty-theme/archive/refs/heads/master.tar.gz"
    refreshPeriod = "168h"
    exact = true
    stripComponents = 2

{{ if eq .chezmoi.os "windows" }}

# WINDOWS

[".local/state/powershell/PSDepend"]
    type = "archive"
    url = "https://github.com/scottbilas/PSDepend/archive/refs/heads/master.tar.gz"
    refreshPeriod = "168h"
    exact = true
    stripComponents = 1

{{ else }}

# UNIX

[".config/bat/extras"]
    type = "archive"
    url = "https://github.com/scottbilas/bat-extras/archive/refs/heads/master.tar.gz"
    refreshPeriod = "168h"
    exact = true
    include = ["*", "*/src/**", "*/lib/**"]
    stripComponents = 1
[".config/ranger/colorschemes"]
    type = "archive"
    url = "https://github.com/alfunx/ranger-colorschemes/archive/refs/heads/master.tar.gz"
    refreshPeriod = "168h"
    exact = true
    include = ["*", "*/*.py"]
    stripComponents = 1
[".local/share/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
[".local/share/repos/prettyping"]
    type = "git-repo"
    url = "https://github.com/denilsonsa/prettyping"
    refreshPeriod = "168h"
[".local/share/repos/dasht"]
    type = "git-repo"
    url = "https://github.com/sunaku/dasht"
    refreshPeriod = "168h"

# windows fonts are available through scoop nerd-fonts bucket
# also note that in nerd font naming, "mono" means "no ligatures", and "book" means "proportional"
# (note that something like "jetbrains mono" will therefore have mono twice in the name for non-ligature fonts..)
[".local/fonts/delugia"]
    type = "archive"
    url = "https://github.com/adam7/delugia-code/releases/latest/download/delugia-complete.zip"
    refreshPeriod = "168h"
    exact = true
    stripComponents = 1
[".local/fonts/jetbrains"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
    refreshPeriod = "168h"
    exact = true
    exclude = ["*Windows Compatible*", "* Mono.ttf"]

{{- end }}
