# COMMON

[".local/docs/nerd-fonts"]
    type = "archive"
    url = "https://github.com/just3ws/nerd-font-cheatsheets/archive/refs/heads/master.tar.gz"
    exact = true
    include = ["*", "*/*.md"]
    stripComponents = 1

{{ if eq .chezmoi.os "windows" }}

# WINDOWS

[".local/state/powershell/PSDepend"]
    type = "archive"
    url = "https://github.com/scottbilas/PSDepend/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1

{{ else }}

# UNIX

[".config/bat/extras"]
    type = "archive"
    url = "https://github.com/scottbilas/bat-extras/archive/refs/heads/master.tar.gz"
    exact = true
    include = ["*", "*/src/**", "*/lib/**"]
    stripComponents = 1
[".config/ranger/colorschemes"]
    type = "archive"
    url = "https://github.com/alfunx/ranger-colorschemes/archive/refs/heads/master.tar.gz"
    exact = true
    include = ["*", "*/*.py"]
    stripComponents = 1
[".local/share/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
[".local/share/repos/prettyping"]
    type = "git-repo"
    url = "https://github.com/denilsonsa/prettyping"
[".local/share/repos/dasht"]
    type = "git-repo"
    url = "https://github.com/sunaku/dasht"

{{- end }}
