{{ if eq .chezmoi.os "windows" }}
[".local/state/powershell/PSDepend"]
    type = "archive"
    url = "https://github.com/scottbilas/PSDepend/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
{{ else }}
[".config/bat/extras"]
    type = "archive"
    url = "https://github.com/scottbilas/bat-extras/archive/refs/heads/master.tar.gz"
    exact = true
    include = ["*", "*/src/**", "*/lib/**"]
    stripComponents = 1
[".local/share/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
[".local/share/repos/prettyping"]
    type = "git-repo"
    url = "https://github.com/denilsonsa/prettyping"
[".local/share/repos/dasht"]
    type = "git-repo"
    url = "https://github.com/sunaku/dasht"
{{- end }}
