{{ if eq .chezmoi.os "windows" }}
[".local/state/powershell/PSDepend"]
    type = "archive"
    url = "https://github.com/scottbilas/PSDepend/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
{{ else }}
[".config/bat/extras"]
    type = "archive"
    # https://github.com/eth-p/bat-extras/releases to find a newer one
    url = "https://github.com/eth-p/bat-extras/releases/download/v2021.08.21/bat-extras-20210821.zip"
    exact = true
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.tar.gz"
    stripComponents = 1
    exact = true
{{- end }}
