#!/usr/bin/env bash
set -euo pipefail

NIXOS_DIR="/etc/nixos"
GITHUB_RAW="https://raw.githubusercontent.com/scottbilas/chezmoi/dev/special/nixos"

usage() {
  cat <<EOF
Usage: curl -fsSL $GITHUB_RAW/bootstrap.sh | sudo bash -s -- [--force] [--dry-run]
   or: sudo bash bootstrap.sh [--force] [--dry-run]

  --force    overwrite existing $NIXOS_DIR/profile.nix
  --dry-run  write files to a temp dir instead of $NIXOS_DIR
EOF
}

OPT_FORCE=false
OPT_DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --help)    usage; exit 0 ;;
    --force)   OPT_FORCE=true ;;
    --dry-run) OPT_DRY_RUN=true ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

# --- checks ---

if [[ $EUID -ne 0 ]] && ! $OPT_DRY_RUN; then
  echo "error: must be run as root (sudo bash bootstrap.sh)"
  exit 1
fi

if [[ ! -f "$NIXOS_DIR/hardware-configuration.nix" ]]; then
  echo "error: $NIXOS_DIR/hardware-configuration.nix not found"\
  echo "Run 'nixos-generate-config' first, then re-run this script"
  exit 1
fi

if [[ -f "$NIXOS_DIR/profile.nix" ]] && ! $OPT_FORCE; then
  echo "error: $NIXOS_DIR/profile.nix already exists"
  echo "Re-run this script with --force to overwrite"
  exit 1
fi

if $OPT_DRY_RUN; then
  NIXOS_DIR=$(mktemp -d)
  echo "dry-run: writing files to $NIXOS_DIR"

  cp "/etc/nixos/hardware-configuration.nix" "$NIXOS_DIR/hardware-configuration.nix"
fi

# --- gather info ---

# need to explicitly route from /dev/tty since stdin is used for the script itself when piped from curl

echo "Select profile:"
echo "  1) pi      - minimal desktop on pi hardware"
echo "  2) minimal - headless, no desktop"
echo "  3) light   - lightweight minimal desktop"
echo "  4) heavy   - full dev environment"
read -rp "Profile [1/2/3/4]: " profile_choice </dev/tty
case "$profile_choice" in
  1) profile=(hardware-pi.nix desktop-light.nix) ;;
  2) profile=(headless-minimal.nix) ;;
  3) profile=(desktop-light.nix) ;;
  4) profile=(desktop-heavy.nix) ;;
  *) echo "Invalid choice"; exit 1 ;;
esac

read -rp "Primary username (joe.bob): " username </dev/tty
read -rp "Computer name (my-machine): " hostname </dev/tty
read -rp "ZeroTier network ID (guid): " zerotier_network </dev/tty
read -rp "SSH public key (ssh-rsa..): " ssh_pubkey </dev/tty

echo "Detecting timezone via ipinfo.io..."
timezone=$(curl -fsSL https://ipinfo.io/timezone 2>/dev/null || true)
if [[ -z "$timezone" ]]; then
  echo "warning: could not detect timezone, defaulting to UTC"
  timezone="UTC"
else
  echo "Detected: $timezone"
fi

# --- generate profile.nix ---

# NOTE: keep profile.example.nix in sync with this heredoc whenever the generated format changes

cat > "$NIXOS_DIR/profile.nix" <<EOF
# generated by $GITHUB_RAW/bootstrap.sh
# $(date '+%Y-%m-%d %H:%M:%S %Z')
#
{ config, lib, pkgs, ... }:

{
  imports = [
$(printf '    ./%s\n' "${profile[@]}")
  ];

  primaryUser = "$username";

  networking.hostName = "$hostname";
  time.timeZone = "$timezone";

  users.users.\${config.primaryUser}.openssh.authorizedKeys.keys = [
    "$ssh_pubkey"
  ];

  services.zerotierone.joinNetworks = [ "$zerotier_network" ];
}
EOF

echo "Generated $NIXOS_DIR/profile.nix"

# --- fetch nix files from github ---

for f in configuration.nix "${profile[@]}"; do
  echo "Fetching $f..."
  curl -fsSL "$GITHUB_RAW/$f" -o "$NIXOS_DIR/$f"
done

echo ""
if $OPT_DRY_RUN; then
  echo "dry-run output: $NIXOS_DIR"
else
  echo "Done. Deploy:"
  echo "  nix-shell -p nix-output-monitor --run \"nixos-rebuild switch |& nom\""
fi
