#!/usr/bin/env bash
set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }

NIXOS_DIR="/etc/nixos"
GITHUB_RAW="https://raw.githubusercontent.com/scottbilas/chezmoi/dev/special/nixos"

usage() {
  cat <<EOF
Usage: curl -fsSL $GITHUB_RAW/bootstrap.sh | sudo bash -s -- [--force] [--dry-run]
   or: sudo bash bootstrap.sh [--force] [--dry-run]

  --force    overwrite existing $NIXOS_DIR/profile.nix
  --dry-run  write files to a temp dir instead of $NIXOS_DIR
EOF
}

OPT_FORCE=false
OPT_DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --help)    usage; exit 0 ;;
    --force)   OPT_FORCE=true ;;
    --dry-run) OPT_DRY_RUN=true ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

# --- checks ---

if $OPT_DRY_RUN; then

  NIXOS_DIR=$(mktemp -d)
  echo "[dry-run] writing files to $NIXOS_DIR"

else

  [[ $EUID -ne 0 ]] &&
    die "must be run as root (sudo bash bootstrap.sh)"

  [[ -f "$NIXOS_DIR/hardware-configuration.nix" ]] ||
    die "NixOS has not been installed yet; run the installer, don't just generate the config"

  [[ -f "$NIXOS_DIR/profile.nix" ]] && ! $OPT_FORCE &&
    die "$NIXOS_DIR/profile.nix already exists -- re-run with --force to overwrite"
fi

# --- gather info ---

# need to explicitly route from /dev/tty since stdin is used for the script itself when piped from curl

echo "Select profile:"
echo "  1) pi      - minimal desktop on pi hardware"
echo "  2) minimal - headless, no desktop"
echo "  3) light   - lightweight minimal desktop"
echo "  4) heavy   - full dev environment"
read -rp "Profile [1/2/3/4]: " profile_choice </dev/tty
case "$profile_choice" in
  1) profile=(hardware-pi.nix desktop-light.nix) ;;
  2) profile=(headless-minimal.nix); use_zerotier=0 ;;
  3) profile=(desktop-light.nix) ;;
  4) profile=(desktop-heavy.nix) ;;
  *) die "invalid choice: $profile_choice" ;;
esac
use_zerotier=${use_zerotier:-1}

prompt_with_default() {
  local prompt="$1" default="$2"
  local hint="${default:+ [$default]}"
  read -rp "${prompt}${hint}: " val </dev/tty
  echo "${val:-$default}"
}

# detect defaults from the live system and prompt
username=$(prompt_with_default "Primary username" "$(id -un 1000)")
fullname=$(prompt_with_default "Full name"        "$(getent passwd 1000 | cut -d: -f5 | cut -d, -f1)")
hostname=$(prompt_with_default "Computer name"    "$(hostname)")
timezone=$(prompt_with_default "Timezone"         "$(timedatectl show --property=Timezone --value)")

read -rp "SSH public key (ssh-rsa ...): " ssh_pubkey </dev/tty
if [[ "$use_zerotier" == "1" ]]; then
  read -rp "ZeroTier network ID (guid): " zerotier_network </dev/tty
fi

# --- generate profile.nix ---

# NOTE: keep profile.example.nix in sync with this heredoc whenever the generated format changes

zerotier_block=""
if [[ "$use_zerotier" == "1" ]]; then
  zerotier_block=$(cat <<ZEROTIER
  services.zerotierone.enable = true;
  services.zerotierone.joinNetworks = [ "$zerotier_network" ];
ZEROTIER
  )
fi

cat > "$NIXOS_DIR/profile.nix" <<EOF
# generated by $GITHUB_RAW/bootstrap.sh
# $(date '+%Y-%m-%d %H:%M:%S %Z')
#
{ config, lib, pkgs, ... }:

{
  imports = [
$(printf '    ./%s\n' "${profile[@]}")
  ];

  primaryUser = "$username";

  networking.hostName = "$hostname";
  time.timeZone = "$timezone";

  users.users.\${config.primaryUser}.openssh.authorizedKeys.keys = [
    "$ssh_pubkey"
  ];
  users.users.\${config.primaryUser}.description = "$fullname";

$zerotier_block
}
EOF

echo "Generated $NIXOS_DIR/profile.nix"

# --- fetch nix files from github ---

for f in configuration.nix "${profile[@]}"; do
  echo "Fetching $f..."
  curl -fsSL "$GITHUB_RAW/$f" -o "$NIXOS_DIR/$f"
done

echo ""
if $OPT_DRY_RUN; then
  echo "dry-run output: $NIXOS_DIR"
else
  echo "Done. Deploy:"
  echo "  sudo nixos-rebuild switch"
fi
