{ config, lib, pkgs, ... }:

{
  options.primaryUser = lib.mkOption { type = lib.types.str; }; # expected to be set in profile

  config = {
    imports = [
      ./hardware-configuration.nix # generated by nixos-generate-config
      ./profile.nix                # generated by bootstrap.sh
    ];

    # core
    system.stateVersion = "25.11"; # once set, never change this (even when updating to newer nixos)
    nix.settings.experimental-features = [ "nix-command" "flakes" ];
    nixpkgs.config.allowUnfree = true;
    i18n.defaultLocale = "en_US.UTF-8";
    system.copySystemConfiguration = true; # auto backup of configuration.nix after a nixos-rebuild switch (find with 'cat $(nixos-option system.copySystemConfiguration)')

    # networking
    networking.networkmanager.enable = true;
    networking.firewall.enable = true;

    # access
    services.zerotierone.enable = true;              # joinNetworks expected in profile.nix
    networking.firewall.allowedUDPPorts = [ 9993 ];  # zerotier's port
    services.openssh.enable = true;                  # authorized keys expected in profile.nix
    networking.firewall.allowedTCPPorts = [ 22 ];    # ssh's port
    security.sudo.enable = true;                     # sudo off by default in nixos
    security.sudo.wheelNeedsPassword = false;        # sudo will not ask for password

    # system programs
    programs.zsh.enable = true;
    environment.systemPackages = with pkgs; [ home-manager ];
    programs.nix-ld.enable = true; # stub dynamic linker so pre-built binaries work (vscode-remote-ssh needs this)

    # primary user setup
    users.users.${config.primaryUser} = {
      isNormalUser = true;
      extraGroups = [ "wheel" "tty" ]; # enables sudo and xrdp
      shell = pkgs.zsh;
    };
  };
}
