{ config, lib, pkgs, ... }:

{
  options.primaryUser = lib.mkOption { type = lib.types.str; }; # expected to be set in profile

  imports = [
    ./hardware-configuration.nix # generated by nixos-generate-config
    ./profile.nix                # generated by bootstrap.sh
  ];

  config = {

    # requred for UEFI systems
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = true;

    # core
    system.stateVersion = "25.11"; # once set, never change this (even when updating to newer nixos)
    nix.settings.experimental-features = [ "nix-command" "flakes" ];
    nixpkgs.config.allowUnfree = true;
    i18n.defaultLocale = "en_US.UTF-8";

    # networking
    networking.networkmanager.enable = true;
    networking.firewall.enable = true;

    # access
    networking.firewall.allowedUDPPorts =            # zerotier's port (if service enabled)
      lib.mkIf config.services.zerotierone.enable [ 9993 ];
    services.openssh.enable = true;                  # authorized keys expected in profile.nix
    networking.firewall.allowedTCPPorts = [ 22 ];    # ssh's port
    security.sudo.enable = true;                     # sudo off by default in nixos
    security.sudo.wheelNeedsPassword = false;        # sudo will not ask for password

    # cap parallelism to avoid OOM on low-memory systems
    nix.settings.max-jobs = 2;
    nix.settings.cores = 2;

    # system programs
    programs.zsh.enable = true;
    environment.systemPackages = with pkgs; [ home-manager ];
    programs.nix-ld.enable = true; # stub dynamic linker so pre-built binaries work (vscode-remote-ssh needs this)

    # primary user setup
    users.users.${config.primaryUser} = {
      isNormalUser = true;
      extraGroups = [ "wheel" "tty" ]; # enables sudo and xrdp
      shell = pkgs.zsh;
    };
  };
}
