# Example profile.nix — generated by bootstrap.sh from user input.
# Keep this file in sync with the heredoc in bootstrap.sh whenever the generated format changes.
#
{ config, lib, pkgs, ... }:

{
  imports = [
    ./hardware-pi.nix    # pi profile
    ./desktop-light.nix  # light/pi profile
    # ./desktop-heavy.nix  # heavy profile
  ];

  primaryUser = "alice";

  networking.hostName = "my-machine";
  time.timeZone = "America/Los_Angeles";

  users.users.${config.primaryUser}.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... alice@example"
  ];

  services.zerotierone.joinNetworks = [ "1234567890abcdef" ];
}
