gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

git:
  paging:
    colorArg: always
    # not yet supported on windows (soon? https://github.com/jesseduffield/lazygit/issues/1453)
    pager: delta --dark --paging=never

update:
  method: never

reporting: off
