#!/usr/bin/env bash
# shellcheck disable=SC1083,SC1091,SC2086,SC3011,SC3024

set -e

# shellcheck disable=SC2034
SUBDIRECTORY_OK=Yes
. git-sh-setup

[ "$DEBUG" ] && set -x

readonly FG_GREEN=$'\e[32m'
readonly FG_BRIGHTBLACK=$'\e[90m'
readonly STYLE_UNDERLINE=$'\e[4m'
readonly STYLE_ITALIC=$'\e[3m'
readonly STYLE_DIM=$'\e[2m'
readonly RESET_ALL=$'\e[0m'

header() {
    local output="${FG_GREEN}${STYLE_UNDERLINE}-- $1 --${RESET_ALL}"
    if [[ -n "$2" ]]; then
        output+=" ${STYLE_ITALIC}${FG_BRIGHTBLACK}$2${RESET_ALL}"
    fi
    echo -e "$output" >&2
}

quiet_warn() {
    echo -e "${STYLE_ITALIC}${STYLE_DIM}[$*]${RESET_ALL}" >&2
}

main() {
    # TODO: move git lx into here

    local REV="" HAS_MAX_COUNT=0

    for arg in "$@"; do
        case "$arg" in
            --max-count=*)
                HAS_MAX_COUNT=1
                ;;
            -* )
                ;;
            *)
                if [[ -n "$REV" ]]; then
                    echo "ERROR: multiple non-option arguments detected" >&2
                    exit 1
                fi
                REV="$arg"
                ;;
        esac
    done

    REV="${REV:-HEAD}"

    # get any commits in upstream that we don't have locally
    UP_ONLY="$(git rev-list --cherry-pick --right-only --first-parent ${REV}..@{u} 2>/dev/null || true)"

    local MAX_UPSTREAM=15

    if [ -n "$UP_ONLY" ]; then
        header UPSTREAM
        COUNT=$(echo "$UP_ONLY" | wc -l | tr -d ' ')

        # only truncate if we want to limit the total count but also have a lot of upstream
        if (( COUNT > MAX_UPSTREAM )) && (( HAS_MAX_COUNT != 0 )); then
            echo "... $((COUNT - MAX_UPSTREAM)) more upstream commits ($(git rev-parse --abbrev-ref @{u})) ..."
            UP_ONLY=$(echo "$UP_ONLY" | head -n $MAX_UPSTREAM)
        fi

        # shellcheck disable=SC2046,2116
        git lx --no-walk $(echo "$UP_ONLY")

        header LOCAL
    elif git rev-parse --abbrev-ref @{u} >/dev/null 2>&1; then
        quiet_warn "No upstream commits found"
    else
        quiet_warn "No upstream branch"
    fi

    git lx --first-parent "$@"
    exit
}

main "$@"
